import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  headerContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    textAlign: 'center',
    paddingTop: 100,
    backgroundColor: '#007bff',
  },
  headerButton: {
    padding: 10,
    paddingBottom:0,
  },
  headerText: {
    color: '#ffffff', 
    textAlign: 'center',
  },
  headerTextLabel: {
    color: '#fff', 
    textAlign: 'center',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',

  },
  activeButton: {
    borderBottomWidth: 2,
    borderBottomColor: '#ffffff',
  },
  activeText: {
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: 300,
    backgroundColor: '#fff',
    borderRadius: 32,
    paddingVertical: 0,
    paddingHorizontal: 0,
    elevation: 12,
    minHeight: 220,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#007bff',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 22,
    paddingVertical: 22,
  },
  modalTitle: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  modalCloseButton: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 20,
    padding: 4,
  },
  menuContent: {
    padding: 18,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderRadius: 14,
    marginBottom: 2,
    paddingHorizontal: 6,
  },
  menuIcon: {
    marginRight: 16,
  },
  menuItemText: {
    fontSize: 19,
    color: '#1976d2',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  menuItemStarText: {
    fontSize: 19,
    color: '#1976d2',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  menuItemExit: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 14,
    marginTop: 6,
    paddingHorizontal: 6,
  },
  menuItemExitText: {
    fontSize: 17,
    color: '#e53935',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  menuSeparator: {
    height: 1,
    backgroundColor: '#e3e8f0',
    marginVertical: 2,
  },
  hamburgerButton: {
    padding: 10,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f3f4',
    borderRadius: 24,
    marginTop: 0,
    paddingHorizontal: 12,
    width: 260,
    height: 44,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 18,
    color: '#222',
    backgroundColor: 'transparent',
    paddingVertical: 0,
  },
});

export default styles;
