import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: '#2C3E50',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 60,
  },
  menu: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    width: 340,
    maxWidth: '90%',
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    marginBottom: 30,
    color: '#E74C3C',
    textShadowColor: '#fff',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    textAlign: 'center',
  },
  formGroup: {
    width: '100%',
    marginBottom: 18,
  },
  label: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 6,
    color: '#333',
  },
  input: {
    backgroundColor: '#f2f2f2',
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#ccc',
    marginBottom: 4,
  },
  dropdown: {
    backgroundColor: '#f2f2f2',
    borderColor: '#ccc',
    borderRadius: 10,
    marginBottom: 4,
  },
  dropdownContainer: {
    borderColor: '#ccc',
    borderRadius: 10,
  },
  // Stili per la gestione dei punteggi
  scoreContainer: {
    flex: 1,
    backgroundColor: '#2C3E50',
    padding: 20,
  },
  scoreTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#E74C3C',
    textAlign: 'center',
    marginBottom: 20,
  },
  playersContainer: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    marginBottom: 20,
  },
  playerCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    minWidth: 120,
    marginHorizontal: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  activePlayer: {
    borderWidth: 3,
    borderColor: '#E74C3C',
  },
  playerName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 10,
  },
  playerScore: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#E74C3C',
    marginBottom: 5,
  },
  playerRemainingLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
  },
  dartBoard: {
    backgroundColor: '#34495E',
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    alignItems: 'center',
  },
  dartBoardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 15,
  },
  instructionText: {
    fontSize: 16,
    color: '#F1C40F',
    textAlign: 'center',
    marginBottom: 10,
    fontWeight: 'bold',
  },
  scoreButtonsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
  },
  scoreButton: {
    backgroundColor: '#E74C3C',
    borderRadius: 10,
    padding: 15,
    minWidth: 60,
    alignItems: 'center',
    marginBottom: 10,
  },
  scoreButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  specialButton: {
    backgroundColor: '#F39C12',
  },
  doubleButton: {
    backgroundColor: '#3498DB',
  },
  tripleButton: {
    backgroundColor: '#9B59B6',
  },
  activeMultiplier: {
    borderWidth: 3,
    borderColor: '#F1C40F',
    shadowColor: '#F1C40F',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 8,
  },
  currentThrowContainer: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 15,
    marginBottom: 20,
    alignItems: 'center',
  },
  currentThrowTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 10,
  },
  currentThrowScore: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#E74C3C',
    marginBottom: 10,
  },
  dartsList: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  dartScore: {
    backgroundColor: '#ECF0F1',
    borderRadius: 8,
    padding: 8,
    minWidth: 40,
    alignItems: 'center',
  },
  dartScoreText: {
    fontSize: 14,
    color: '#2C3E50',
    fontWeight: 'bold',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  actionButton: {
    backgroundColor: '#95A5A6',
    borderRadius: 10,
    padding: 15,
    minWidth: 100,
    alignItems: 'center',
  },
  undoButton: {
    backgroundColor: '#F39C12',
  },
  nextPlayerButton: {
    backgroundColor: '#27AE60',
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Stili per la vittoria
  victoryContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2C3E50',
    padding: 20,
  },
  victoryContent: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 30,
    width: '90%',
    maxWidth: 400,
  },
  victoryMessage: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#E74C3C',
    textAlign: 'center',
    marginBottom: 20,
  },
  fireworks: {
    width: 200,
    height: 200,
    marginBottom: 20,
  },
  finalScoresContainer: {
    backgroundColor: '#ECF0F1',
    borderRadius: 10,
    padding: 15,
    marginBottom: 20,
    width: '100%',
  },
  finalScoresTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    marginBottom: 10,
  },
  finalScoresRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  finalScoresColumn: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  finalScoreText: {
    fontSize: 16,
    color: '#34495E',
    fontWeight: '600',
  },
  statsContainer: {
    backgroundColor: '#E8F4FD',
    borderRadius: 10,
    padding: 15,
    marginBottom: 20,
    width: '100%',
  },
  statsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    marginBottom: 10,
  },
  statsText: {
    fontSize: 14,
    color: '#34495E',
    textAlign: 'center',
    marginBottom: 5,
  },
  buttonContainer: {
    flexDirection: 'column',
    width: '100%',
    gap: 10,
  },
  victoryButton: {
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
  },
  primaryButton: {
    backgroundColor: '#E74C3C',
  },
  secondaryButton: {
    backgroundColor: '#3498DB',
  },
  backButton: {
    backgroundColor: '#95A5A6',
  },
  victoryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default styles;
